POST https://example.com/comments/1 HTTP/1.1

###

GET https://example.com/topics/1 HTTP/1.1


###
#Game info
GET http://localhost:3000/game HTTP/1.1
content-type: application/json

{
    "type": "info",
    "game_id": "abc"
}

###

#Start game post request
POST http://localhost:3000/game HTTP/1.1
content-type: application/json

{
    "type": "new_game",
    "test_mode": "true"
}

###

POST http://localhost:3000/game HTTP/1.1
content-type: application/json

{
    "type": "ready",
    "game_id": "abc"
}



###
POST http://localhost:3000/game HTTP/1.1
content-type: application/json

{
    "type": "bid",
    "game_id": "abc",
    "player": "north",
    "bid": "7nt" 
    
}

#//change to current player
//change to new bid, for example: suits: c, d, h, s, nt with number before
#// example: 1nc, 2s are both valid bids, s2 is not. 